### ISSUE TITLE
Unable to create association with User entity

### ISSUE THREAD

**Issue by alexander-shustanov** [Haulmont/jmix-old#475]
Try start an attached project. [untitled43.zip](https://github.com/jmix-framework/jmix/files/4710951/untitled43.zip)
AR:
```
Exception Description: [class com.company.untitled43.entity.Foo] uses a non-entity [class io.jmix.security.entity.User] as target entity in the relationship attribute [field user].
	at org.eclipse.persistence.exceptions.EntityManagerSetupException.predeployFailed(EntityManagerSetupException.java:233)
	... 8 more
Caused by: Exception [EclipseLink-7250] (Eclipse Persistence Services - 2.7.7.1-jmix): org.eclipse.persistence.exceptions.ValidationException
Exception Description: [class com.company.untitled43.entity.Foo] uses a non-entity [class io.jmix.security.entity.User] as target entity in the relationship attribute [field user].
	at org.eclipse.persistence.exceptions.ValidationException.nonEntityTargetInRelationship(ValidationException.java:1383)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.RelationshipAccessor.getReferenceDescriptor(RelationshipAccessor.java:569)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.ObjectAccessor.processForeignKeyRelationship(ObjectAccessor.java:678)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.ObjectAccessor.processOwningMappingKeys(ObjectAccessor.java:752)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.ManyToOneAccessor.process(ManyToOneAccessor.java:130)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processOwningRelationshipAccessors(MetadataProject.java:1666)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage3(MetadataProject.java:1919)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:584)
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processORMetadata(PersistenceUnitProcessor.java:629)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2006)
	... 6 more
```

**Comment by knstvk** [comment]
Will be resolved in #583
